export const CURRENCIES = [
  ['CAD', 'Canadian dollar'],
  ['USD', 'US dollar'],
  ['EUR', 'Euro'],
  ['GBP', 'British pound'],
  ['INR', 'Indian rupee'],
  ['AUD', 'Australian dollar'],
  ['NZD', 'New Zealand dollar'],
  ['JPY', 'Japanese yen'],
  ['CNY', 'Chinese yuan'],
  ['CHF', 'Swiss franc'],
  ['SGD', 'Singapore dollar'],
  ['HKD', 'Hong Kong dollar'],
  ['MXN', 'Mexican peso'],
  ['BRL', 'Brazilian real'],
  ['ZAR', 'South African rand'],
  ['AED', 'UAE dirham'],
  ['SEK', 'Swedish krona'],
  ['NOK', 'Norwegian krone'],
  ['PHP', 'Philippine peso'],
  ['NGN', 'Nigerian naira'],
];
